# Generated by Django 4.2 on 2026-01-30 10:07

import customer.managers
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customer_set', related_query_name='customer', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customer_permission_set', related_query_name='customer', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', customer.managers.CustomerManager()),
            ],
        ),
    ]
