# Generated by Django 4.2 on 2026-01-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
