# Generated by Django 4.2 on 2026-01-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_is_active_alter_staff_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='comments',
        ),
    ]
