# Generated by Django 4.2 on 2026-02-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deleted_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='deleted_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
