# Generated by Django 4.2 on 2026-01-30 10:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('VERIFY', 'Verify email'), ('RESET', 'Reset password')], max_length=10)),
                ('actor', models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff')], max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('SENT', 'Sent'), ('VERIFIED', 'Verified')], default='SENT', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'actor', 'purpose'], name='email_otp_e_email_9bb9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'actor'], name='email_otp_e_email_1476db_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailotp',
            constraint=models.UniqueConstraint(fields=('email', 'actor', 'purpose'), name='uniq_email_actor_purpose_otp'),
        ),
    ]
