# Generated by Django 4.2 on 2026-01-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('VERIFY', 'Verify email'), ('RESET', 'Reset password')], max_length=10)),
                ('state', models.CharField(choices=[('SEND', 'Send'), ('VERIFIED', 'Verified'), ('USED', 'Used')], default='SEND', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
